### ISSUE TITLE
recipe-list

### ISSUE THREAD

**Issue by Luxa23** [Luxa23/capstone-project#1]
### value description / statement
As a *user*
I want to *save a list of recipes*
so that *I don't forget them*.

### Description

<img width="531" alt="recipe-list" src="https://user-images.githubusercontent.com/102022862/169538779-1c3ae16f-f1f3-4324-b8b9-87485d622a50.png">

### Acceptance criteria
- if I click on save and nothing has been entered in input, the user should get an info about this
- if I enter a text starting with spaces, trim should be used

#
- [x] the input must be "required"
- [x] max-length must be 100 characters
- [x] text should show dots in line when needed so that horizontal scrolling is not required
- [x] whitespace should be trimmed
- [x] the list should scroll behind the form 

### Tasks
- [x] Create a branch
- [x] Create component "RecipeListEntry"
- [x] Create component "Button"
- [x] Create component "RecipeForm"
- [x] Add logic to create recipes from form
- [x] Check on a real device

### Complexity
large

**Comment by Luxa23** [comment]
### value description / statement
As a *user*
I want to *save a list of recipes*
so that *I don't forget them*.

### Description
- images (wireframe / excalidraw / figma) von allen Zuständen

### Acceptance criteria
- if I click on save and nothing has been entered in input, the input field should be highlighted
   - first draw: use "required" in html instead of perfect design; functionality more important than design
   --> the input must be required
- if I enter a text starting with spaces, trim should be used

- [ ] the input must be "required"
- [ ] max-length must be 100 characters
- [ ] text should wrap on space characters
- [ ] text should scroll in a single line if needed / wrap anyways / show dots ...
- [ ] whitespace should be trimmed
- [ ] the list scroll should scroll behind the form (form has a white background)

### Complexity
low, medium, high

**Comment by raimartontsch** [comment]
Hi @Luxa23 ! 

Looks good so far for your first user story. I still have some questions and hope resolving them helps you ;) 

When you say component you mean an actual component? Or are you talking about input fields or a button for example? This may sound a little bit petty but makes a difference in the work load and your data structure. 

If you do mean components maybe you should consider to break down this user story into smaller pieces. For example  to write a single user story for (bigger) components. Especially when it comes to building a form this is in general a kind of   bigger deal.    

Also it helps to think about what happens on the page when it is used. For example would it be an acceptance criteria, if the text which is typed in appears as item in the list above?  If so, feel free to add it ;) 

To be honest. Especially in the beginning writing user stories sucks. But I am sure it will help you structure your project and your work flow. At least for me it worked out  ;)  

One last tip: In my experience it is good to have small and exact user stories. In general this also breaks down the complexity and makes it much easier to work with. 

Hope this helps. In case you have any questions, please let me know ;)

**Comment by Luxa23** [comment]
hi @raimartontsch,

thanks a lot for reviewing and all the advice!!

Indeed, I meant components but they currently only consist of the mentioned pieces:

"RecipeListEntry" --> text
"Button" --> button with two states
"RecipeForm" --> one input field for the recipe title

Later on, I would like to add more complex stuff to them. E.g. an image to the "RecipeListEntry" or more input fields to the form.
