### ISSUE TITLE
toast: the new recipe was saved

### ISSUE THREAD

**Issue by Luxa23** [Luxa23/capstone-project#22]
As a user
I want to be reassured that my entry was saved
so that I can continue with the next one.

### Description

After the user successfully pressed the "Save-Button" a small layover is shown with the text "The entry was saved".

### AC

- [x] after having pressed the "Save" Button, a confirmation with the text "The entry was saved" appears.
- [x] the confirmation disappears by itself after one second

### Tasks
- [x] create confirmation box component
- [x] create a styled component for the confirmation box
- [x] add logic to component
- [x] add logic to save-button

### Complexity
small

**Comment by CJAkkuec** [comment]
This is very nit-picky, but "layover" might not be the term you're looking for. As far as I know, "layover" describes how long you'll be staying at an airport between flights. The term you're looking for instead might be "notification". I'd actually suggest a simple notification instead of a modal/etc, because you very well might run into more instances of wanting to notify the user about something, and modals are a bit clunky for that specific purpose. If you need any recommendations, let me know. :)
