### ISSUE TITLE
Change wording of recipe titles

### ISSUE THREAD

**Issue by Luxa23** [Luxa23/capstone-project#3]
### Value description / statement

As a user 
I want to change the recipe titles
so that I can correct mistakes or add words that I forgot.

### Description

<img width="485" alt="02-change recipe title" src="https://user-images.githubusercontent.com/102022862/169713805-3f8b3ef9-f251-4a97-861d-0b40115f2fff.png">

### AC

- [ ] when clicking on the pen next to the recipe title, the user can change the title
- [ ] when clicking the tick, the new text will be saved and shown in the list

### Tasks

- [ ] create new branch
- [ ] add pen icon to "RecipeListEntry"
- [ ] add tick icon to "RecipeListEntry"
- [ ] add logic to icons
- [ ] add logic to text field
- [ ] make sure that change is saved in local storage

### Complexity
- medium

**Comment by marcbendixen** [comment]
Hey 👋 
Good idea to add this feature to your list. I have nothing to add here because it's a really good and well structured user story for me 👍
